### ISSUE TITLE
Detecting if the user is a member

### ISSUE THREAD

**Issue by Strikegently** [powerbot/RSBot-API#1023]
Currently, we can check the world but it doesn't work if it's a member in a F2P world.

**Comment by IITC** [comment]
I feel like we should consolidate cache requests into a single issue.. lol

**Comment by Robert-G** [comment]
ctx.widgets.component(1607, 8).text().toLowerCase().contains("member until");

Probably not the sort of thing you want in the clients API, but will work nicely for local use till such a function is available.

**Comment by Paris** [comment]
@Timer is it necessary to have a hook for this when @Robert-G's solution above should work?

**Comment by iitc** [comment]
Pretty sure @Robert-G's solution is RS3 only. I don't think such a notice exists on OS.

**Comment by NexPB** [comment]
@iitc runescape had this member until since 2007 back in the days pritty sure OS should have it aswell.

**Comment by iitc** [comment]
@nexPB, never noticed it then.. Lol..

**Comment by iitc** [comment]
They've done some login changes since release of old school so it's something to look into. I know what you're referencing but idk if that still exists.

**Comment by iitc** [comment]
Wait. Actually this may be a valid solution, if the widget text persists after logging in.

**Comment by Timer** [comment]
@Paris I'm pretty sure it requires a hook, the gui hook is unreliable.

**Comment by rs-sliske** [comment]
on rs3, f2p accounts have the subscribe wigit (1477, 557), (1477, 558)

**Comment by rs-sliske** [comment]
any news on this?

**Comment by Strikegently** [comment]
Re-opening this as it is essential for future improvements.
