### ISSUE TITLE
Max depth search for reachable() and getPath()

### ISSUE THREAD

**Issue by Strikegently** [powerbot/RSBot-API#1188]
If you are checking `reachable()` in a large place, like a dungeon, especially one with a lot of obstacles, it can take quite a long time to process.

A quick solution would be to add an optional maximum search depth; i.e. if the calculated path exceeds a certain length, stop searching. 

The pathfinding isn't open source so I can't.

**Comment by Timer** [comment]
The pathing isn't what takes time, it's the collision map generation. #1262 should really help this.

**Comment by ArtificialPB** [comment]
Additionally, you could add collision map caching and make it expire after one of these conditions is met:
- Cache is older than a certain time limit (~1200ms),
- Player moves,
- Map base tile changes.

**Comment by Paris** [comment]
Is this still relevant to `rt4`?
