### ISSUE TITLE
Check if object is rendered on screen

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/RSBot-API#1191]
Is there any way you could add a method to check if object is rendered on screen? 
![renderdistance](https://cloud.githubusercontent.com/assets/4672155/12080935/6d50bc44-b26b-11e5-8c07-166d0bfedcae.png)

**Comment by Timer** [comment]
@ArtificialPB is this rt6? if so it should already take this into account with inViewport.

**Comment by ArtificialPB** [comment]
Yes this is rt6. I've experienced this myself not long ago and I got users reporting the script is sometimes stuck trying to click objects that are not rendered. @Timer

**Comment by Ragezors** [comment]
Can confirm this happens, objects slightly out of the rendered area are (sometimes) still treated as inViewPort.

**Comment by Timer** [comment]
so if it's just *hardly* out of viewport it's not interactable? I'll see if I can tweak the calculation...

**Comment by ArtificialPB** [comment]
@Timer If it's only hardly out of viewport it is interactable. The problem is that no matter how far away you are from desired object, it always returns true if you're turned to it and no HUD components are blocking it. This returns true for inViewport for Furnace in Edgeville even though it's at least 10 tiles out of rendered distance: 
![renderissue](https://cloud.githubusercontent.com/assets/4672155/12089684/ebc21bd2-b2e7-11e5-80e5-0d13bd14394a.png)
I took a look at the inViewport method in Game class for rt6 and as far as I can tell, it only looks if any of the HUD components are blocking it.

**Comment by Timer** [comment]
@ArtificialPB that's because this should handle it: https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/Game.java#L268

**Comment by Paris** [comment]
As `rt6` is no longer supported this issue is closed.
