### ISSUE TITLE
Default script selection

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/RSBot-API#1244]
Default script selection for new users to make their experience with RSBot better, also a way to link directly to the OS tab of /scripts would be really nice to stop users trying to use RS3 scripts on OS.

If this goes ahead I also think there should be a button introduced linking to /scripts (as currently the only way to it from the client is if you have no scripts).

For OSRS I would suggest
ASmither OS
ACrafting OS
CCooker
MasterChopper OS
SAIO Fighter
Super Magic
xAgility
xAlchemy
xMiner

**Comment by NexPB** [comment]
I like this idea

**Comment by Paris** [comment]
Will rework in #2142.
