### ISSUE TITLE
Capture account details while logged in

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/RSBot-API#1299]
I notice on OSRS it will randomly get 'command received: zap' and log you out, sometimes it is 5 minutes in, sometimes 6 hours. I always forget to add an account, and I think it's because you select the script then press play so it'd be better if there was like a pop-up alerting you if you haven't selected an account (maybe give them the option to add one, select one, or continue[run script])

alternatively maybe just lay it out different so that the add/select account part is above or before the select script part so you automatically focus on it instead of skipping it naturally.

obviously not very important, but it helps with the overall user experience

**Comment by Timer** [comment]
Don't we capture the details and relogin?

**Comment by ChrisBPB** [comment]
I think you do on RS3

**Comment by Paris** [comment]
@Timer do the login capture for automatic re-login on OSRS too?

**Comment by Timer** [comment]
Yeah, that's what I'm planning on @Paris. I thought we did it already though.

**Comment by Paris** [comment]
Seems like we don't @Timer, so I'll let you take this one.

**Comment by Timer** [comment]
Yeah I'll take care of this.

**Comment by Habibeche** [comment]
Thank you for the advice, of course, will care about it, my friend

**Comment by stumpy3toes** [comment]
I could really do with this for one of my scripts, any chance this could happen soon? Seems like a fairly simple and quick fix considering it already happens with RS3

**Comment by ChrisBPB** [comment]
What happens is on OSRS when you log out the credentials are cleared, so on script launch we need to perform something, probably create a game account if it doesn't exist, or load the existing one if it does.
