### ISSUE TITLE
Component color request

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/RSBot-API#1439]
Request for a method for grabbing component color/color id, if possible. There is currently only a method for getting text color. This will allow us to find more components dynamically.

**Comment by Moosheplusplus** [comment]
How would this vary from texture ID? Are there components composed of only a single color?

**Comment by ArtificialPB** [comment]
I was looking at the osrs special attack bar, which turns blue when you don't have enough energy to use it. The blue line has no texture id.

**Comment by benpoulson** [comment]
@AshGreh Could we add this to the list of future hooks we'd like to add. It should be an easy one to expose all the hooks we have for widgets.

For now I'm closing this ticket. However, I've made a note to comment on it when this specific hook has been implemented. We have upcoming work to implement a big backlog of new and missing hooks.

**Comment by AshGreh** [comment]
Added it to the hook's list.
