### ISSUE TITLE
Viewable#inViewport() inefficient load times and inaccurate

### ISSUE THREAD

**Issue by Moosheplusplus** [powerbot/RSBot-API#1478]
Filtering a query with .viewable() will cause extreme load times (15 seconds to 70 seconds).

`ctx.objects.select(30).viewable()`:

> [INFO] mooshe.rt4.TestScript: 170 Objects selected. Took 19707ms

`ctx.objects.select().viewable()`:

> [INFO] mooshe.rt4.TestScript: 1037 Objects selected. Took 50109ms

Objects somehow outside of a 30 tile radius are somehow being validated, which is also inaccurate.

**Comment by ArtificialPB** [comment]
This also applies to rt6. The part that takes the longest to execute is BoundingModel#nextPoint().

**Comment by Mkerian10** [comment]
Can this be closed @ChrisBPB
