### ISSUE TITLE
High-resolution support for OSRS

### ISSUE THREAD

**Issue by Strikegently** [powerbot/RSBot-API#1560]
High-resolutions work on Mac, but not Windows or Linux. This should be addressed.

![](http://i.imgur.com/PHY6XVf.png)

**Comment by Moosheplusplus** [comment]
This is an underlying issue with the system disabling High DPI Display Scaling. The [RuneScape Knowledgebase](https://support.runescape.com/hc/en-gb/articles/207003879-Interface-scaling-issues-on-high-DPI-monitors-Windows-10) even addresses this.

**Comment by Mkerian10** [comment]
So should this be closed?

**Comment by benpoulson** [comment]
I'm closing this ticket due to inactivity.
Please reply to this ticket if you believe the issue is still ongoing.
