### ISSUE TITLE
Documentation importing

### ISSUE THREAD

**Issue by Strikegently** [powerbot/RSBot-API#1610]
Most IDEs have an option to set up remote JavaDoc links to allow for documentation inside the editor.
However, the requests are filtered so they do not work.

Either:
- Allow connecting to the JavaDoc site from within the editors, or;
- Offer a zip/jar of the JavaDoc pages that users could manually import;

**Comment by Mkerian10** [comment]
Could we revisit this? Shouldn't be too difficult even though it's only a minor QoL update.

**Comment by chazmuzz** [comment]
@Mkerian10 if you still need this, I've got this working by adding the rsbot-api as a maven dependency using jitpack.  eg:

```xml
  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>com.github.powerbot</groupId>
      <artifactId>powerbot</artifactId>
      <version>rsbot-api-SNAPSHOT</version>
    </dependency>
  </dependencies>
```

Now VSCode picks up the doc comments:

<img width="1020" alt="Screenshot 2019-05-07 at 16 08 13" src="https://user-images.githubusercontent.com/883595/57310808-5f948700-70e2-11e9-9867-907ef5f318a3.png">

**Comment by benpoulson** [comment]
I'm closing this ticket due to inactivity.
Going forwards, I'll add a note to see if we can either bundle javadocs into our jars, or export supplementary javadoc jars to go along with our releases.

Please reply to this ticket if you believe the issue is still ongoing.
