### ISSUE TITLE
isSpellSelected

### ISSUE THREAD

**Issue by Strikegently** [powerbot/RSBot-API#1837]
Equivalent of the RT6 `client.isSpellSelected` is needed for OSRS.

**Comment by Mkerian10** [comment]
Should fixed no?

**Comment by ChrisBPB** [comment]
he wanted a hook for rt6 and rt4 but I am told this doesn't exist, but we have methods to achieve this already

**Comment by Strikegently** [comment]
Re-opening this. The hook does exist in RT4.

**Comment by Paris** [comment]
Merged into #2133.
