### ISSUE TITLE
Improve "Configure Breaks"

### ISSUE THREAD

**Issue by Stemuli** [powerbot/RSBot-API#1966]
Few ideas:

-Saving break patterns

-Editing break patterns easily

-Show "break after","break time" and type in same pop up.

-In the break list, show total online time, total idle time, and so on. Of course, total run time requires that there is a end defined.
example:
Total run time: 24h 00min
Total online time: 6h 47min
Total idle time: 0h 42min
Active botting: 6h 05min

Major improvement idea:
Make the break configuration more visual. e.g. 8h, 12h, 24h(or maybe even a week?) time window shown, and botting time drawn with red, breaks with blue. (Just an example). Adding more breaks by highlighting areas(Example; Outlook calendar). This would require some work..

Any of these improvements could be made a VIP option, to make the VIP a little more desirable.

**Comment by Paris** [comment]
Merging into #1965.
