### ISSUE TITLE
Improve mis-click prevention

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/RSBot-API#1971]
Mis-clicking is normally fine and a solid antiban tool, but there are situations where it'd be nice to get rid of it. 

I'd like to propose an overloaded option for interacting and forcing it to confirm that it's clicking the desired point. Currently we're checking based on a MenuFilter, but unless I'm mistaken that's not taking into account left clicks. The naive to do that is change the Filter<Point> in apply() to dynamically check that the point is in the npc bounds.

The issue here is this takes significantly longer, it takes about 3500 ns to check the points, while it takes about 4-6 ms to check if the input location is within the npc's bounds.

Another option could be seeing which menu item is currently being displayed as the primary (the one that shows up in the top left).

**Comment by ChrisBPB** [comment]
if there's 50 people stood next to a fire and you left click the people (on position of the fire) then you still click the fire although the menu item will not be fire related, is that how it works or am I remembering wrong?

**Comment by ChrisBPB** [comment]
fire is a bad example because it's not interactable

**Comment by Mkerian10** [comment]
@ChrisBPB I don't believe you example holds true. There may be a case where something similar would mess it up though.
