### ISSUE TITLE
[RS3] Script crashes upon polling nearest object sometimes.

### ISSUE THREAD

**Issue by anwar6953** [powerbot/RSBot-API#1978]
The [piece of code](https://github.com/powerbot/powerbot/blob/scripts/src/manbearpigcat/scripts/potatofarmer/tasks/AntiBan.java#L42):
```java
GameObject obj = ctx.objects.select().nearest().poll();
```

The stacktrace for the exception which causes the script to crash:
```
[SEVERE] Exception: java.lang.IllegalArgumentException: Comparison method violates its general contract!
org.powerbot.script.AbstractQuery.sort(AbstractQuery.java:119)
org.powerbot.script.rt6.MobileIdNameQuery.nearest(MobileIdNameQuery.java:82)
org.powerbot.script.rt6.MobileIdNameQuery.nearest(MobileIdNameQuery.java:74)
manbearpigcat.scripts.potatofarmer.tasks.AntiBan.execute(AntiBan.java:42)
manbearpigcat.scripts.potatofarmer.PotatoPicker.poll(PotatoPicker.java:120)
org.powerbot.script.PollingScript$6.run(PollingScript.java:77)
```

**Comment by ChrisBPB** [comment]
Where are you when you do this? Need to be able to reproduce to fix.

**Comment by anwar6953** [comment]
I'll try to reproduce it and give you coordinates.

**Comment by anwar6953** [comment]
I'm able to reproduce this, but not consistently. Still working on that.

**Comment by ChrisBPB** [comment]
Ok thanks

**Comment by Beerato** [comment]
You forgot to put id(ObjectID) like this
`GameObject obj = ctx.objects.select().id(1278).nearest().poll();`
This is for normal trees.
