### ISSUE TITLE
rt4 Camera goes whack when middle-click dragging over painted components

### ISSUE THREAD

**Issue by tanlines** [powerbot/RSBot-API#1999]
Easiest way to replicate:
Under View, select any that paints text on screen.
Middle click drag over text and camera will spazz out.

Also happens when using ctx.input.drag() while a script is running.

**Comment by ChrisBPB** [comment]
The mouse uses the same canvas to draw as click so I am not sure if this will be resolvable

**Comment by ChrisBPB** [comment]
1 canvas is hacky, 2 would be terrible. Sadly we can't hook the games canvas itself without it requiring some injection.

I will look into this when I get time anyway to see if there is anything we can do but I am not too hopeful

**Comment by AshGreh** [comment]
@ChrisBPB is there a property/method to completely disable paint when your script is running( even view options should stop being painted on the canvas )? If not, would it be possible to bring about such a thing?

**Comment by Paris** [comment]
Related to #1447.
