### ISSUE TITLE
SDN usability issues

### ISSUE THREAD

**Issue by tanlines** [powerbot/RSBot-API#2013]
Currently the only way to filter scripts is by Free/Premium/VIP and a search bar.

To search by category, one has to recall the names for each skill, and there might be other categories other than skills (e.g. Combat). Non-english speaking users in particular may struggle with this.

Searching "crafting" will come up with both Runecrafting and Crafting scripts.

No natural ordering for scripts increases search time. Either alphabetical, by users or alphatically by category would make it faster to find what you want.

Script writers aren't able to set their own categories, resulting in some scripts being put into the wrong category.

No multi-language support. From the comments I receive on the forums, I believe a good portion of the userbase doesn't speak English.

No ALT text on icons for vision impaired users.

**Comment by ChrisBPB** [comment]
Script are random to avoid bias, and to avoid people using silly methods to get to the top of the list.

Categories are guessed by keywords, if you encounter an issue then you may choose to edit your description or let us know so we can alter our keywords.

We have never received a comment from a non-english speaker saying they are not able to do what they want on the SDN page. We have plenty of users and customers from non-english speaking countries over the past 9 years for this to seem like a non-issue.

You can't put alt text on a div.


We may be able to add category filters, I don't think it's required but it could be a byproduct of making the category clearer in general.

All this said, we don't know if the SDN is staying as it is so we won't rework it until we know it's not changing. The SDN is a low priority task given it has worked for so long with very very few complaints from end users.

**Comment by Paris** [comment]
Merged into #2142.
