### ISSUE TITLE
Add support for MenuListener

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/RSBot-API#2019]
I'm not sure if this'd require injection or if we'd have another way of intercepting the instructions. But adding support for something like a MenuListener would be great. An example of this would be what's used here: https://github.com/runelite/runelite/pull/6242/files

It'd help out with tracking some things that are typically a little more difficult to track, such as rune essence pouches as well

**Comment by Mkerian10** [comment]
We could fire an event every time interact or click is called. I don't think that'd miss any cases.

**Comment by ChrisBPB** [comment]
The menu options of what you hover are updated every so many ms or are you talking about a different menu?

**Comment by benpoulson** [comment]
I've just looked into adding the Runelite implementation of the MenuOptionClicked event and it would indeed require a form of injection into the `menuAction` method in `client`.

I'll try to come up with a workaround.

**Comment by Paris** [comment]
In that case I'll merge this issue into #2133.
