### ISSUE TITLE
Input.defocus() & Input.focus() unusable

### ISSUE THREAD

**Issue by kThisIsCvpv** [powerbot/RSBot-API#2026]
Client does not properly defocus nor focus.
This was tested in OSRS. 

Test Parameters: 
- Right Click Object
- Menu Pops Up

Expected Output: 
- Defocus makes the menu that pops up disappear.

Actual Output:
- Nothing happens.

I'm attempting to stimulate an "AFK" scenario with this method.

**Comment by kThisIsCvpv** [comment]
Suppose I open a menu and alt-tab to another screen; the menu closes. I don't think defocus is solely triggered by clicking off the screen.

Would there be a better alternative to simulate this interaction in the current API?

**Comment by tanlines** [comment]
Chris I remember you said something about not calling actions after you've called defocus.

At a later date, you said that called another action should call refocus. 

Could you clarify which case it is?

**Comment by ChrisBPB** [comment]
@kThisIsCvpv  I don't know what to tell you. The FocusEvent is sent to the RS client window to tell it that focus has been lost. I will do some debugging and ensure the event it truly sent and isn't breaking early for some reason.

As for not calling actions @tanlines, focus() is called before any event is sent so you do not need to worry about refocusing yourself

**Comment by ChrisBPB** [comment]
the event is sent successfully to the game applet

**Comment by benpoulson** [comment]
To to inactivity I am going to close this issue. If you believe the issue has not been resolved, then feel free to comment here again.
