### ISSUE TITLE
LocalPath.getCosts adds the same cost to every tile

### ISSUE THREAD

**Issue by tanlines** [powerbot/RSBot-API#2050]
The methods `Tile.getBoundaryObject()`, `getWallObject()` always return `true` for every tile. `Tile.getObjectsLength` works, but doesn't detect doors so is largely useless when generating a path since the flags will already indicate the tile is blocked and it won't be explored.
The other methods `getItemPile()`, `getFloorObject()` don't seem to work.

This is adding [unnecessary overhead](https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/LocalPath.java#L71) to `Movement.reachable`. Reduced ~150ms to ~30ms when I removed it.

**Comment by Paris** [comment]
The link no longer works, is this still an issue?

**Comment by tanlines** [comment]
Fairly certain it is, don't remember seeing any commits to that file, though I've been using my own custom implementation for a while now.
