### ISSUE TITLE
Breaking system does not have indicator

### ISSUE THREAD

**Issue by tanlines** [powerbot/RSBot-API#2051]
In all of my scripts I have a failsafe that checks if a specific condition hasn't been met after a few minutes e.g. exp gained.

When someone sets up a break, the timers keep running and I have no way to check when I should be pausing my timers, causing my failsafes to trip and terminate the script.

**Comment by ChrisBPB** [comment]
if your override of the method is called and you return true then it is taking a break

**Comment by tanlines** [comment]
I feel like I've asked this before. Can you make a thread in Resources on the forums with an example?

**Comment by ChrisBPB** [comment]
> 	canBreak()
Called if the user specified run duration has been reached, triggerig Script.State.STOP if true is returned.



this is from the docs, you just override the method just as you would with start for example, if you don't want the default behaviour

**Comment by Paris** [comment]
Merged into #1965.
