### ISSUE TITLE
Client hook chunks

### ISSUE THREAD

**Issue by kThisIsCvpv** [powerbot/RSBot-API#2061]
I need an additional variable in the RT4 library to make a map generating script that involves chunk data.

There should be a variable in `org.powerbot.bot.rt4.client.Client` that has the signature `int[][][]`.

It stores data on the instance chunks currently loaded in the client using 4 logical left shifts. 

On RL, it is called `Client.getInstanceTemplateChunks()`
On another client, it is called `Client.getChunksInfo()`

The 3D array should be of length 4x13x13 ( or something similar ) and stores data via coordinates [z][x][y].

**Comment by benpoulson** [comment]
Currently in 184, it can be located under under the following;

```
class : client
field: gs
descriptor: [[[I
static: true
multiplier: 0
```

**Comment by benpoulson** [comment]
@AshGreh Could we add this to the list of future hooks we'd like to add, as I agree it could be a good hook to add. 

For now I'm closing this ticket. However, I've made a note to comment on it when this specific hook has been implemented. We have upcoming work to implement a big backlog of new and missing hooks.

**Comment by AshGreh** [comment]
Added to the list of hooks.
