### ISSUE TITLE
Script initialization exceptions

### ISSUE THREAD

**Issue by AshGreh** [powerbot/RSBot-API#2076]
The above exception is being thrown a few SDN scripts since the revert of house keeping.

https://www.powerbot.org/community/topic/1352374-scripts-will-not-start-when-start-is-clicked/
https://www.powerbot.org/community/topic/1352369-bot-or-scriptissue/

**Comment by Paris** [comment]
Thanks for the report, changed some backend things and both those scripts should work now.

**Comment by Paris** [comment]
Reopening: author of script needs to fix his imports it seems like.

**Comment by benpoulson** [comment]
I believe this issue can be closed. Feel free to reply here again if not!
