### ISSUE TITLE
Component positions incorrect in resizable mode

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/RSBot-API#2083]
Looks like one of the recent rt4 game updates caused screen point translation offset for components:
<img width="372" alt="Screenshot 2019-10-08 at 21 01 41" src="https://user-images.githubusercontent.com/4672155/66424965-e988a900-ea0e-11e9-828a-9fecb7182b65.png">

Seems to be offset only with resizeable sidebar:

<img width="392" alt="Screenshot 2019-10-08 at 21 06 52" src="https://user-images.githubusercontent.com/4672155/66425350-b2ff5e00-ea0f-11e9-8d7c-be67fa36d21d.png">

**Comment by benpoulson** [comment]
I'll take a look at this, although I worry this may require new hook work.

**Comment by AshGreh** [comment]
Coma and I created a temporary patch for widgets. @benpoulson we might have to revisit the widget parent parsing rather than looking for a new hook.

**Comment by ArtificialPB** [comment]
@AshGreh Yes.

**Comment by AshGreh** [comment]
@benpoulson when are the new widget hooks coming?

**Comment by Paris** [comment]
I reckon I fixed this in 5cfbdb356 so after it gets a thorough testing I'll make a release.
