### ISSUE TITLE
Bank pin interface stopping scripts

### ISSUE THREAD

**Issue by iDznPB** [powerbot/RSBot-API#2084]
https://github.com/powerbot/RSBot-API/blob/master/src/main/java/org/powerbot/bot/rt4/BankPin.java
 
ctx.getPin() returns null even if I supply it with a pin thus stops.

**Comment by benpoulson** [comment]
Windows, MacOS, Linux?

**Comment by iDznPB** [comment]
Java version: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
RSBot version: 7114
Game version: OSRS
Operating System: macOS Mojave 10.14.5

**Comment by AshGreh** [comment]
@iDznPB hey, sorry for the delay. I have found the issue and will be fixing it by the end of the day.

**Comment by AshGreh** [comment]
Closing as it has been resolved.
