### ISSUE TITLE
Movement.distance doesn't respect gates

### ISSUE THREAD

**Issue by Mkerian10** [powerbot/RSBot-API#2090]
`Movement.distance` is supposed to give the amount of steps in order to reach a certain target vs. standard euclidean distance.

However when a gate is closed and you attempt to find the distance between the player and the destination tile it'll treat the gate as if it's open. I tested this on three separate gates and gate models, held true for all of them.

Doors work correctly, and if the door is closed the correct distance will be given.

This method uses `LocalPath.Graph`, so I'd guess it's an issue with the flags.

**Comment by k0na** [comment]
Where did you test this?

**Comment by Mkerian10** [comment]
@k0na Edgeville dungeon wilderness gate. I also tested it on some misc. gates around draynor and lumbridge
