### ISSUE TITLE
Game tab broken

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2091]
Revision needed for the boolean method for when on certain game tabs. e.g. `ctx.game.tab() == Tab.LOGOUT` returns `false` when on the tab.

**Comment by benpoulson** [comment]
Will attempt to replicate this issue.

**Comment by AshGreh** [comment]
@RZME couldn't replicate this issue. Could you give me example scenarios where I would be able to see this?

**Comment by Strikegently** [comment]
Can't replicate.
