### ISSUE TITLE
GeItem class

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2093]
Requests for item prices needs to be revised or serve as a fail-safe. 
Requests take up too much time and too many requests lead to a temporary IP block which restricts dev to load certain prices

*Removed*
I'm already doing this by using a CRON Job to download it to my server (every x minutes) and then do a request at start when loading prices

It is way faster (Loads price information of all items in few seconds)
Approach would be to just have the json somewhere clientsided and when a dev calls the price method for instance it would get the price instantly.

It also has more price information for each item. i.e. average buy quantity, store price etc.

**Comment by benpoulson** [comment]
Completely agree with this. I'm not sure whether we proxy these requests currently, but personally, I'd see repeated requests to a RS API as a warning to jagex to check the requesting user more thoroughly. 

Should be pretty simple to do a hourly poll of osb/rsb/runelite/osrsbox data and host it from an API.

**Comment by AshGreh** [comment]
@benpoulson I remember reading a post by @Paris about the request being funnelled through rsbot's server for faster results. Time to switch to per user req to osb or something similar I guess.

**Comment by Paris** [comment]
We don't need to use a third party because we should proxy this on our servers, which I can easily do soon.

**Comment by Paris** [comment]
@RZME is there a source where all the item prices are listed together or is the only option to request every item then combine it?

**Comment by RZME** [comment]
>@RZME is there a source where all the item prices are listed together or is the only option to request every item then combine it?

@Paris The source is a json file that contains extensive price info for every item (so no need to request multiple times, just download it once every x hours) . I linked it in this post. Currently using it myself, i download it every hour to my server and parse it in my scripts. Within like 1 second price info of all items are parsed and mapped
