### ISSUE TITLE
unrecognized gameobjects and npcs

### ISSUE THREAD

**Issue by gutizia** [powerbot/RSBot-API#2102]
since new version was released I've found all herb/allotment/flower patches to have wrong id's with all actions + name = null. I've tried deleting cache, reinstalling rsbot and restarting pc and even tried with a different pc all together. always same wrong id. in addition to these, ornate jewellery box in POH's are also wrong and tool leprechaun had id = 0, but name is recognized. both pcs tested on shared same ip and was on windows 10

**Comment by Strikegently** [comment]
#2101
