### ISSUE TITLE
Withdraw options broken

### ISSUE THREAD

**Issue by iDznPB** [powerbot/RSBot-API#2106]
Selected left click withdraw option isn't taken into account when trying to withdraw.

For example, I had _Withdraw X_ selected as my left click option with the value set at 14.

`ctx.bank.withdraw(ID, 1);` withdrew 14 as it just left clicked rather than either changing the withdraw option then left clicking or choosing withdraw 1 from the menu.

**Comment by ChrisBPB** [comment]
withdraw-1 and withdraw-14 are seen as the same so need stricter filtering on this

you can make use of withdrawModeQuantity if you wish in the meantime to make sure it is set to 1
