### ISSUE TITLE
click() and interact() don't consider if the cursor is already within bounds

### ISSUE THREAD

**Issue by yekrep** [powerbot/RSBot-API#2117]
The `click()` and `interact()` methods of interactives do not consider whether the cursor is already within the bounds of the interactive. This causes the mouse to move every time the script calls the method, leading to erratic behavior (as if the player has hiccups) including occasionally clicking near the edge and outside of the bounds. In order to better mimic human-like behavior, ideally the mouse would seldom move and then only barely.

**Comment by yekrep** [comment]
https://github.com/powerbot/RSBot-API/commit/b3b0554680d99f6319bdbfa311ce8de56f004ee7

**Comment by Strikegently** [comment]
The problem would be that, if the bounds are not entirely accurate and the mouse is at a position that is not within the bounds, it will repeatedly fail to click because it isn't moving the mouse at all.

We may revisit this if we hook models.
