### ISSUE TITLE
Login-handler not fully functional

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2127]
doesn't click the login widget
![unknown (1)](https://user-images.githubusercontent.com/35044712/72804629-16c13600-3c51-11ea-94f4-857adec57212.png)

**Comment by ChrisBPB** [comment]
ctx.components.select().text("CLICK HERE TO PLAY").poll() 

should work, not currently on laptop with local build to test

**Comment by AshGreh** [comment]
@RZME I was hoping to have optimized query out by now, but didn't get time. So, instead, I will look into a component query cache and change the internal handling of that. Sorry for the delay.

**Comment by Strikegently** [comment]
I can't replicate this. The login handler already uses Component Query to find the login button.
If you have any info that may be beneficial, post it and I'll reopen this issue.
