### ISSUE TITLE
ctx.game.logout() not working

### ISSUE THREAD

**Issue by gutizia** [powerbot/RSBot-API#2129]
tried in both fixed screen and resizeable, they only changed tab to LOGOUT, but nothing happened after that, this is the case for being in the normal LOGOUT tab and worlds list. also another issue i've noticed is when you are on Kourend Favour, the bounds for the  QUESTS tab is too far down and to the left so calling ctx.game.tab(QUESTS) won't work properly

**Comment by AshGreh** [comment]
@gutizia what do you mean by on Kourend Favour? Sorry, i'm a bit out of sync.
