### ISSUE TITLE
Bank.WithdrawModeQuantity not returning correct values

### ISSUE THREAD

**Issue by iDznPB** [powerbot/RSBot-API#2130]
```
	public Amount withdrawModeQuantity() {
		final int withdrawModeNumber = ctx.varpbits.varpbit(Constants.BANK_QUANTITY);
		switch(withdrawModeNumber) {
			case Constants.BANK_WITHDRAW_MODE_ONE: return Amount.ONE;
			case Constants.BANK_WITHDRAW_MODE_FIVE: return Amount.FIVE;
			case Constants.BANK_WITHDRAW_MODE_TEN: return Amount.TEN;
			case Constants.BANK_WITHDRAW_MODE_X: return Amount.X;
			case Constants.BANK_WITHDRAW_MODE_ALL: return Amount.ALL;
			default: return Amount.PLACEHOLDER;
		}
	}
```

Defaults to PLACEHOLDER 

Wasn't really sure what values it's supposed to be as the ones I found weren't even close but if it helps, I got 1666 still correct varp but 
1: 1408 (0x580)
5: 1412 (0x584)
10: 1416 (0x588)
x: 1420 (0x58c)
All: 1424 (0x590)

**Comment by ArtificialPB** [comment]
This should be the correct way to parse withdraw mode: `value >> 2 & 0x7`. Then, map the constants from 0 to 4, where `0 = withdraw 1` and `4 = withdraw all`.
