### ISSUE TITLE
Bank widget component ids should be updated

### ISSUE THREAD

**Issue by Elvarg42** [powerbot/RSBot-API#2146]
Hi,

in today's release Jagex updated something regarding banking. Because of that banking with RSBot doesn't work anymore. 

If I'm not mistaken only these bank widget component ids should be updated [here](https://github.com/powerbot/RSBot-API/blob/master/src/main/java/org/powerbot/script/rt4/Constants.java#L29). New values should be:
```Java
public static final int BANK_DEPOSIT_INVENTORY = 41;
public static final int BANK_DEPOSIT_EQUIPMENT = 43;
```

**Comment by ChrisBPB** [comment]
waiting for release
