### ISSUE TITLE
InViewport method not working properly

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2163]
![30b4a8d0c597afec42fd54343fdb364e](https://user-images.githubusercontent.com/35044712/84606368-e9964e00-aea5-11ea-9586-65d3d0cbff6b.png)

```
00:09 osrs.RSlayer.RSlayer: Obstacle name: Gate | Distance: 4.0
00:09 osrs.RSlayer.RSlayer: Obstacle name: Gate | Distance: 4.123105625617661
00:09 osrs.RSlayer.RSlayer: Obstacle name: Stile | Distance: 9.0
00:09 osrs.RSlayer.RSlayer: Next tile not reachable. Handling Gate
Gate
inViewport: false
```
Should handle the object -> inViewport() returns false -> stuck
version: 8.017

**Comment by Strikegently** [comment]
I can't replicate it. I stood exactly where you are and checked the gate and it worked fine.
That logging though:
```Gate | Distance: 4.0```
You are definitely not 4 tiles away from that gate. You've got the wrong object.
