### ISSUE TITLE
Bounds not being scaled

### ISSUE THREAD

**Issue by ChrisBPB** [powerbot/RSBot-API#2166]
https://i.gyazo.com/ca2ad4028812a84f48388e5e74694cdb.png

Script writers also confused whether them settings bounds overrides the new models or if they are only used should the model fail to load from the cache

**Comment by ChrisBPB** [comment]
@benpoulson says that is actually not the calf model in the picture but the cow, so it is using the wrong model. I can't really see if that's the case or not

**Comment by iDznPB** [comment]
Just to add some more cases and evidence.
Smolcano is Zolcano's pet, yet it's showing the bounds for the actual boss not the pet.
https://gyazo.com/72c4bee810caba8a444fdb41f9336895
https://gyazo.com/8b1253d10d275960bb5a896d0570e2be

**Comment by k0na** [comment]
![image](https://user-images.githubusercontent.com/1911217/84654674-e3d55280-af0f-11ea-85a0-310e2f171231.png)
Done

**Comment by k0na** [comment]
@ChrisBPB custom model bounds _can_ be set by the script writer, however, this should only be done if they have verified that the cache model somehow doesn't work as they would like it to.

**Comment by iDznPB** [comment]
@k0na Bounds aren't just used to define the entire entity, they're also used to defined a specific area to click from that object.

**Comment by k0na** [comment]
@iDznPB I know. Let me clarify my previous comment: if the cache model fails to provide useful points for clicking, the script writer can manually define what area/bounds to use instead (and if they choose to do so, the cache model will be ignored).
