### ISSUE TITLE
v8.017 broken

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2170]
v8.017 is broken e.g. some boundary objects are not registered.
Can at least we revert back to v8.016? a fixed new release would also suffice.
Kind of pointless having to share v8.016 to every specific user.

**Comment by Herdware** [comment]
Also experiencing this, since 8.0.17 I see users running the script for less than a minute and giving up. Tested it myself and it seems to be related to banker bounds. A revert to 8.0.16 or release of 8.0.18 would be great.

**Comment by ChrisBPB** [comment]
@k0na @constt do we need to revert or is this a simple fix

**Comment by ChrisBPB** [comment]
@RZME @Herdware every bank?

**Comment by ChrisBPB** [comment]
Nevermind this appears to have already been fixed, we just need w release to be made

**Comment by ChrisBPB** [comment]
Released, pls reply if there’s an issue
