### ISSUE TITLE
Implement grandexchange notification ?

### ISSUE THREAD

**Issue by swatarianess** [powerbot/RSBot-API#847]
The Grandexchange Hook has been the same for more than half a decade. Would it be possible to implement it? (RT4 and RT6)

Request: Implement the hook.

It contains information such as what items are being sold, amount sold, percentage complete etc. Would be good to see it utilized by scripts situated around Varrock.

**Comment by benpoulson** [comment]
We have upcoming work to implement a big backlog of new and missing hooks.
It's a contiversial area to hook, but if @Paris is happy for us to do so we can add GE hooks into the TODO list. @AshGreh 

For now I'm closing this ticket. However, I've made a note to comment on it when these specific hooks has been implemented.
